name: cron
on:
  push:
    branches:
      - main
    paths:
      - 'packages/cron/**'
      - '.github/workflows/cron*'
      - 'packages/db/**'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'packages/cron/**'
      - '.github/workflows/cron*'
      - 'packages/db/**'
      - 'package-lock.json'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm test --workspace packages/cron
        env:
          PG_REST_URL: ${{secrets.PG_REST_URL}}
          PG_REST_JWT: ${{secrets.PG_REST_JWT}}
          PG_CONNECTION: ${{secrets.PG_CONNECTION}}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: tag-release
        with:
          path: packages/cron
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: cron
